import type { Metadata } from "next";
import "./globals.css";

import { Inter } from "next/font/google";

import { AppSidebar } from "@/components/app-sidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

import { JotaiDevTools } from "@/components/jotai-dev-tools";
import { QueryProvider } from "@/components/providers/query-provider";
import { ReactNode } from "react";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <>
      <JotaiDevTools />
      <html lang="en">
        <body className={`${inter.className} antialiased`}>
          <QueryProvider>
            <SidebarProvider>
              <AppSidebar />
              <SidebarInset className="gap-5 p-5">{children}</SidebarInset>
            </SidebarProvider>
          </QueryProvider>
        </body>
      </html>
    </>
  );
}
