import type { Metadata } from "next";
import './globals.css';

import { Inter } from 'next/font/google';

import { AppSidebar } from '@/components/app-sidebar';
import { PageHeader } from '@/components/page-header';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';

import { JotaiDevTools } from '../components/jotai-dev-tools';

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <JotaiDevTools />
      <html lang="en">
        <body className={`${inter.className} antialiased`}>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <PageHeader />
              {children}
            </SidebarInset>
          </SidebarProvider>
        </body>
      </html>
    </>
  );
}
