import type { Metadata } from "next";
import './globals.css';

import { Inter } from 'next/font/google';

import { JotaiDevTools } from '../components/JotaiDevTools';

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <JotaiDevTools />
      <html lang="en">
        <body className={`${inter.className} antialiased`}>{children}</body>
      </html>
    </>
  );
}
